nginx:
  ports:
    - 8888:80
  image: nginx
  volumes:
    - ./nginx:/etc/nginx/conf.d
"ecs-watch":
  env_file:
    docker.env
  image: ecs-watch:develop
  volumes: 
    - ./nginx.tmpl:/templates/nginx.tmpl
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - nginx
  command: "track --template-generate --template-input-file s3://test-staging-account/nginx.tmpl --template-output-file /etc/nginx/conf.d/default.conf"
  #command: "track --template-generate --template-input-file /templates/nginx.tmpl --template-output-file /etc/nginx/conf.d/default.conf"
  privileged: true
